package com.vince.ex;
/**
 * 异常处理
 * @company
 * @author autuo
 * @description
 */
public class ExceptionDemo {

	public static void main(String[] args) {
		div(10, 2);
		method();
	}
	/**
	 * 除法运算
	 * @param num1
	 * @param num2
	 */
	private static void div(int num1, int num2) {
		int[] arr = {1,2,3,4,5};
		try {
			System.out.println(arr[4]);
			arr = null;
			System.out.println(arr[4]);
			int result = num1/num2;
			System.out.println("result="+result);
		}catch(ArithmeticException e) {
			System.out.println("尊敬的用户除数不能为零");
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("数组下标越界");
		}catch(NullPointerException e) {
			System.out.println("空指针异常");
		}catch(Exception e) {
			System.out.println("出错了");
		}finally {
			System.out.println("运行结束");
		}
	}
	
	private static int method() {
		int a = 10;
		int b = 5;
		try {
			System.out.println(a);
			System.out.println(b);
			int c = a/b;
			System.out.println(c);
			return c;
		}catch(Exception e) {
			e.printStackTrace();
		}
	}

}
